# Generated by Django 5.0.4 on 2024-04-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livre_pint_app', '0002_imagem_user_foto_perfil_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='foto_perfil.png', null=True, upload_to='foto_perfil'),
        ),
    ]
