# Generated by Django 5.0.4 on 2024-04-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
